version: '6.0'

services:
    database:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Test_Password1"
            ACCEPT_EULA: "Y"